### ISSUE TITLE
README for tms-extract

### ISSUE THREAD

**Issue by micahwalter** [mplusmuseum/mplusmuseum-tms-extract#1]

**Comment by micahwalter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [README for CLI](https://trello.com/c/pBSQFu6C/7-readme-for-cli)

**Comment by micahwalter** [comment]
Trying out Trello integration....

**Comment by revdancatt** [comment]
This should probably just be a general README, for information on how to install and how to run.

**Comment by revdancatt** [comment]
Now that the code works in a slightly different way the instructions will need to be updated to reflect the _new_ way of doing things.

Initially running the import/upsert script on the command line with additional parameters, then with parameters.
