### ISSUE TITLE
When a new developer key is created push to GraphQL

### ISSUE THREAD

**Issue by revdancatt** [mplusmuseum/mplusmuseum-tms-extract#102]
When we create a new developer we give them an API key. We should let the GraphQL server know about any new API keys so it can validate them when calls are made.

**Comment by jedahan** [comment]
Some quick finds re: auth0 and graphql

* [Step by step for making posts](https://auth0.com/blog/building-an-instagram-clone-with-graphql-and-auth0/)

* [Quick outline of what creating a token might look like *through* graphql](https://medium.com/the-graphqlhub/graphql-and-authentication-b73aed34bbeb)
