### ISSUE TITLE
Make it so it works on AWS Lambda

### ISSUE THREAD

**Issue by jedahan** [mplusmuseum/mplusmuseum-tms-extract#5]
_From @micahwalter on October 4, 2017 22:22_

I'd like this to be useable from the command line .. obviously with options, parameters and help text

I'd also like this to work inside of AWS Lambda ( perhaps via the serverless framework ) so we can set it up to react to an updated XML on S3, or call it via AWS API Gateway.. 

_Copied from original issue: jedahan/tmsxmlparser#9_

**Comment by revdancatt** [comment]
Splitting this into two task, 1 working on Lambda and 2 working from the command line.
