### ISSUE TITLE
Log error messages when connecting to ElasticSearch into a log file.

### ISSUE THREAD

**Issue by revdancatt** [mplusmuseum/mplusmuseum-tms-extract#54]
When we make the connection to the ElasticSearch in the ping code we are suppressing error messages so they don't keep spitting out onto console and filling the logs (if running with PM2 etc.).

At the moment any errors are turned off (on pings), we should really put them into their own log file.

**Comment by micahwalter** [comment]
Can we use Logstash for all of this?
