### ISSUE TITLE
Display missing images

### ISSUE THREAD

**Issue by revdancatt** [mplusmuseum/mplusmuseum-tms-extract#81]
When we bring in images the file doesn't always match the location exported, we flag these as missing. Now we need to display the missing one in the dashboard and steps the user can take to fix it.

"Hi @micahwalter, looking through the spelunker, I'm finding that a number of objects from the Sigg Online don't have images but should. Some links below:

Not sure where the TMS folder these images are pulling from are from?

https://collections.mplus.org.hk/collections/objects/2207
https://collections.mplus.org.hk/collections/objects/2091
https://collections.mplus.org.hk/collections/objects/3011
https://collections.mplus.org.hk/collections/objects/2802

On the other hand, some do:
https://collections.mplus.org.hk/collections/objects/2223"

**Comment by micahwalter** [comment]
cc'ing @dianewang - we moved this issue to here.
